DynamicMenuFromDatabase/Models/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace DynamicMenuFromDatabase.Models
{
    public class DatabaseContexts:DbContext
    {
        public DbSet<MenuMst> MenuMsts { get; set; }
    }
}

DynamicMenuFromDatabase/Models/MenuMst.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DynamicMenuFromDatabase.Models
{
    public class MenuMst
    {
        public MenuMst()
        {
            MenuList = new List<MenuMst>();
        }
        [Key]
        public int ID { get; set; }
        public string MenuText { get; set; }
        public int? PerentID { get; set; }
        public string MenuUrl { get; set; }
        [NotMapped]
       public List<MenuMst> MenuList { get; set; }

        public List<MenuMst> MenuTree(List<MenuMst> menuList,int? parentid )
        {
            return menuList.Where(x => x.PerentID == parentid).Select(
               x=> new MenuMst
               {
                   ID=x.ID,
                   MenuText=x.MenuText,
                   PerentID=x.PerentID,
                   MenuUrl=x.MenuUrl,
                   MenuList=MenuTree(menuList,x.ID)
                   
               }).ToList();
        }

    }
}

DynamicMenuFromDatabase/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DynamicMenuFromDatabase.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

DynamicMenuFromDatabase/Controllers/MenuController.cs
using DynamicMenuFromDatabase.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DynamicMenuFromDatabase.Controllers
{
    public class MenuController : Controller
    {
        DatabaseContexts _db = new DatabaseContexts();
        MenuMst menu = new MenuMst();
       public PartialViewResult GenerateMenu()
        {
            var menuList = _db.MenuMsts.ToList();
            var menuForDisplay = menu.MenuTree(menuList, null);
            return PartialView("GenerateMenu", menuForDisplay);
        }
    }
}

DynamicMenuFromDatabase/Views/Home/Index.cshtml
<h3>Dynamic Menu From Database in mvc using entity framework</h3>

DynamicMenuFromDatabase/Views/Menu/GenerateMenu.cshtml
@model IEnumerable<DynamicMenuFromDatabase.Models.MenuMst>


<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>

        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav">@ShowMenu(Model)</ul>
        </div>
        </div>
</nav>

@helper ShowMenu(IEnumerable<DynamicMenuFromDatabase.Models.MenuMst> menulist)
{
    foreach (var menu in menulist)
    {
        <li class="@(menu.MenuList.Any() ? "dropdown" : "")">
           
        @if (menu.MenuList.Any())
            {
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"   aria-expanded="false">
                    @menu.MenuText
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    @ShowMenu(menu.MenuList)
                </ul>
            }
            else
            {
                <a @Url.Action(menu.MenuUrl)>@menu.MenuText</a>
            }
        </li>
    }
}

DynamicMenuFromDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar-fixed-top">
        <div class="container">
            
          @{ Html.RenderAction("GenerateMenu", "Menu");}
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>